### PR TITLE
Updated default registration templates

### LINKED ISSUE #1: Finish templates for default registration

### PR DESCRIPTION
**Pull request by ericamador**
Finished writing the default registration templates. Updated the requirements on django-cripsy-forms to >= 1.4 because the crispy template pack "bootstrap3" was introduced in 1.4. Closes #1

### CODE REVIEW

**Comment by pydanny** [comment]
While this effort is appreciated, you do know that django-registration is past it's end-of-life, right? I'm happy to merge this in but I also think I should cap the maximum Django version this package allows. What do you think?

**Comment by ericamador** [comment]
I'm unsure about a maximum Django version, since django-registration remains fairly popular and it seems many still plan to use it with Django 1.6 once compatibility fixes are merged, such as:
https://bitbucket.org/ubernostrum/django-registration/pull-request/63/django-16-compatibility-fix-auth-views/diff

Thanks for the quick response though!

**Comment by pydanny** [comment]
I don't think you understand. There have been numerous pull requests to fix these outstanding issues and the maintainer isn't accepting them. Hasn't for months, and the last pull request broke custom user model integrations. In fact, the author says he's done with it on his blog and refuses to assign anyone to replace himself.

Again, I'm willing to accept this pull request (or grant you commit rights), but there are better, more secure options that are alive and well-maintained, chief amongst them is django-allauth.

**Comment by ericamador** [comment]
Thanks for the information. I saw the outstanding pull requests, but I hadn't realized that he had completely abandoned the project and refused to assign a maintainer to replace himself. Feel free to close this pull request or merge it with a cap of Django <= 1.5 if you feel that it may helpful to someone in the future.

**Pull request closed without merging**
